### PR TITLE
bump mc version

### LINKED ISSUE #842: release/update classical&analysis for mathcomp 1.16
Currently both https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-classical/coq-mathcomp-classical.0.6.0/opam and https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mathcomp-analysis/coq-mathcomp-analysis.0.6.0/opam conflict with 1.16

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

- fixes #842

##### Things done/to do

~~- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`~~
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

### CODE REVIEW

**Comment by proux01** [comment]
@affeldt-aist this should update the CI (`.nix/config.nix` and `.github/workflows/docker-action.yml`, but I'm afraid that won't work until we get HB for 8.17).

Maybe we could do this in two steps:
* first support MC 1.16 on Coq <= 8.16
* then support Coq 8.17

**Comment by affeldt-aist** [comment]
You are right. Let us make another release for Coq 8.17.

**Comment by affeldt-aist** [comment]
We should maybe keep somewhere the information on how to bump the version:
1. update opam files for `classical` and `analysis`
2. update `.nix/config.nix`
3. update `.github/workflows/docker-action.yml`

**Comment by proux01** [comment]
Maybe (I often forget point 1. ;-) )

**Comment by affeldt-aist** [comment]
I added a small wiki page https://github.com/math-comp/analysis/wiki/How-to-bump

**Comment by proux01** [comment]
CI green, let's merge

**Pull request merged**
