### PR TITLE
[CI] adding master

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by proux01** [comment]
Should we also add 8.15 and master to the Docker CI?

**Comment by proux01** [comment]
@CohenCyril maybe using branch `coq-master` of coq-elpi could help?

**Comment by proux01** [comment]
@CohenCyril feel free to cherry pick the three commits in https://github.com/math-comp/analysis/pull/510
At least the Docker CI goes through for master.
The 8.15 job is failing due to a bug in 8.15+rc1 that is fixed in 8.15 branch so hopefully 8.15.0 will be ok.
The `Nix CI for bundle master / coq-elpi` job is now ok but there is still an error with the `Nix CI for bundle master / mathcomp-analysis` job I don't get (it seems a redirection to /dev/null is hidding the error).

**Comment by CohenCyril** [comment]
> @CohenCyril feel free to cherry pick the three commits in #510 At least the Docker CI goes through for master. The 8.15 job is failing due to a bug in 8.15+rc1 that is fixed in 8.15 branch so hopefully 8.15.0 will be ok. The `Nix CI for bundle master / coq-elpi` job is now ok but there is still an error with the `Nix CI for bundle master / mathcomp-analysis` job I don't get (it seems a redirection to /dev/null is hidding the error).

Thanks, cherry-picked them all and squahed.

**Pull request merged**
