### PR TITLE
Renaming flim to cvg

### LINKED ISSUE #29: naming of flim_add
https://github.com/math-comp/analysis/blob/aa351f34edbf0c45fc88cd5528749803bf1e8b3f/hierarchy.v#L1490

Is that a good name? With that name, I was rather expecting a lemma such as
Lemma lim_add (F : filter_on X) (f g : X -> Y) (a b : Y) :
  f @ F --> a -> g @ F --> b -> (f + g) @ F --> a + b.
(no prod, following flim_const).

### PR DESCRIPTION
**Pull request by CohenCyril**
Fixes #29

- `cvg` corresponds to `_ --> _`
- `lim` corresponds to `lim _`
- `continuous`  corresponds to continuity
- some suffixes _opp, _add ... renamed to N, D, ...

Apply this substitution **before** rebasing on top of this commit:
```bash
sed -i -f etc/pr193.sed **/*.v
```

@math-comp/analysis what do you think about this conventions?

### CODE REVIEW

**Comment by affeldt-aist** [comment]
Wouldn't `appr` be more natural as a prefix?

**Comment by mkerjean** [comment]
Do you have an example of simplifying allowed by this renaming ?

**Comment by CohenCyril** [comment]
@affeldt-aist 
> Wouldn't `appr` be more natural as a prefix?

Maybe, I don't know, `appr` makes me think of `app` as in `oapp`, buut maybe it is not that bad...

@mkerjean 
> Do you have an example of simplifying allowed by this renaming ?

The main simplification is documentation and consistency of notations. Right now `lim_add`, `lim_opp`... should be named `flim_add`, `flim_opp` instead. But the visual distinction between `lim` and `flim` is not clear enough in my opinion, and explaining `flim` goes through the history of coquelicot, where it was called `filterlim`, and since `f @ x --> y` is supposed to be handled without the explicit use of filters in most cases, it seems unnatural to rely on a name which contains the word `filter` in it, hence the switch to `approaches` or rather an abbreviation of it.

**Comment by affeldt-aist** [comment]
What about using "tends to" instead of "appraoches" and abbreviate it as "tto"?

**Comment by CohenCyril** [comment]
So should we have a poll?
/polls `flim` `apr` `appr` `tto` `tendsto` `cvg`

**Comment by CohenCyril** [comment]
I force pushed to show how it would look with `cvg`

**Comment by affeldt-aist** [comment]
But then shouldn't, e.g., `lim_scale` become `cvgZ`?

**Comment by CohenCyril** [comment]
If it's too confusing, `cvg := F --> lim F` could be renamed `is_cvg := F --> lim F`.

**Comment by CohenCyril** [comment]
> But then shouldn't, e.g., `lim_scale` become `cvgZ`?

I did several mistakes in the sed script, they should be fixed now. Can you refresh and tell me it you see a problem?

**Comment by CohenCyril** [comment]
The checks finally pass, and I am happy with the result. @mkerjean what do you think?

**Comment by mkerjean** [comment]
`cvg` seems great (sorry, I've been busy with job applications).

**Comment by CohenCyril** [comment]
> `cvg` seems great

Thanks for your input :smiley: 

> (sorry, I've been busy with job applications).

good luck!!

**Pull request merged**
