### PR TITLE
Hierarchy builder merged

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

This PR is the result of merging the branch `hierarchy-builder` into the `master` corresponding to tag `0.7.0`.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [x] added corresponding documentation in the headers

##### Compatibility with MathComp 2.0

- [ ] I added the label `TODO: HB port` to make sure someone ports this PR to
      the `hierarchy-builder` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

### CODE REVIEW

**Comment by affeldt-aist** [comment]
NB:
- the last commit is a fix and is clearly a leftover, it would have been nicer without it but this is not a big issue
- here are a few additions to `CHANGELOG_UNRELEASED.md` that are genuine
but it is still incomplete

**Comment by proux01** [comment]
I guess this is just to run CI and not intended to be merged? In which case it should be a draft PR, to avoid merging it inadvertently.

**Comment by proux01** [comment]
We'll have to add 8.19 to the CI, but this can be done after merging https://github.com/math-comp/analysis/pull/951

**Comment by affeldt-aist** [comment]
I have completed a changelog but you'd better take a look @proux01 @CohenCyril @zstone1 .
Though it is fairly exhaustive, there certainly are technical points you'd like to explain a bit more. 

It just remains to update the documentation which should be less boring and you're en route to the next release.

**Comment by proux01** [comment]
Honestly, I trust you here. At first glance it looks reasonable but I don't have the patience to carefully review the changelog (the remaining is ok). So as far as I'm concerned, you can push this on master.

**Comment by affeldt-aist** [comment]
The last commit contains an update of the doc.
This is intended to be a minimal update: just to make sure that we do not mention identifiers in the headers that do not exist anymore.

If you are ok with the changelog (@proux01 seems to be) and with the doc update (that may be a good timing to add things you care about), we can do a release of MathComp-Analysis 1.0 before friday.

**Pull request merged**
