### PR TITLE
Fix notation and scope usage and generalize ereals

### PR DESCRIPTION
**Pull request by pi8027**
cc: @affeldt-aist

### CODE REVIEW

**Comment by affeldt-aist** [comment]
Why not PR on branch analysis_270? (analysis_270_integration is regularly rebased on anslysis_270)

**Comment by affeldt-aist** [comment]
Also, is it important to redefine the comparison operators in scope ereal_scope? Why not use order_scope (or %O) when one needs them?

**Comment by pi8027** [comment]
@affeldt-aist 

> Why not PR on branch analysis_270? (analysis_270_integration is regularly rebased on anslysis_270)

There are 3 branches including `270` and this was so confusing to me (I still don't understand the difference between them), but I can reopen this for `analysis_270`.

> Also, is it important to redefine the comparison operators in scope ereal_scope? Why not use order_scope (or %O) when one needs them?

`order_scope` defines the `0` and `1` notations which mean the bottom and top of lattices. It's better to do not use `order_scope` to reason about ereals.

**Comment by affeldt-aist** [comment]
> There are 3 branches including `270` and this was so confusing to me (I still don't understand the difference between them), but I can reopen this for `analysis_270`.

Sorry about that. `analysis_270_*` are branches that build upon `analysis_270`, each working on a different aspect but the common basis is `analysis_270`. (We could at least delete `analysis_270_integral`). 
 
> > Also, is it important to redefine the comparison operators in scope ereal_scope? Why not use order_scope (or %O) when one needs them?
> 
> `order_scope` defines the `0` and `1` notations which mean the bottom and top of lattices. It's better to do not use `order_scope` to reason about ereals.

Ok, I see. I was happy enough using 0%R and 1%R here and there, since so far the need for order_scope was limited.

**Comment by pi8027** [comment]
> Ok, I see. I was happy enough using 0%R and 1%R here and there, since so far the need for order_scope was limited.

IMO, error messages produced by `(0 < x)%O` where `x : (R : numDomainType)` is difficult enough to let us lose time a lot. Those specialized notations save our time.

**Comment by affeldt-aist** [comment]
> IMO, error messages produced by `(0 < x)%O` where `x : (R : numDomainType)` is difficult enough to let us lose time a lot. Those specialized notations save our time.

Ok. Otesudesuga, is it ok to PR on analysis_270?

**Comment by pi8027** [comment]
Yes.

**Pull request closed without merging**
