### PR TITLE
Mathcomp master hausdorff

### PR DESCRIPTION
**Pull request by mkerjean**
A certain number of lemmas on the unicity of limits are using the predicate "close" on pseudoMetricTypes and normedModTypes (e.g flim_map_lim).

This PR aims at generalizing these lemmas to the level of Hausdorff topological types.

### CODE REVIEW

**Comment by mkerjean** [comment]
The main content of this PR is going to be merged into PR#177. What remains are few lemmas dealing with within (section within) which were useful in other developments. Should they be added to topology.v ?

**Comment by CohenCyril** [comment]
> The main content of this PR is going to be merged into PR#177. What remains are few lemmas dealing with within (section within) which were useful in other developments. Should they be added to topology.v ?

yes sure

**Comment by affeldt-aist** [comment]
What about closing this PR now that is has been split between PR #177 and PR #182 ?

**Comment by mkerjean** [comment]
PR closed since it has split between PR #177 and PR #182.

**Comment by mkerjean** [comment]
PR closed since it has split between PR #177 and PR #182.

**Pull request closed without merging**
