### PR TITLE
fix {ae m, P} notation

### PR DESCRIPTION
**Pull request by affeldt-aist**
so that integral_sketch compiles

### CODE REVIEW

**Comment by CohenCyril** [comment]
O had already fixed that :-/

**Comment by affeldt-aist** [comment]
> I had already fixed that :-/

I am not sure what happened but I realized when rebasing integral_sketch that the fix has been partly undone. My bad. :cat2:

**Comment by CohenCyril** [comment]
> I am not sure what happened but I realized when rebasing integral_sketch that the fix has been partly undone. My bad.

maybe you undid more :cry:

**Review by CohenCyril — APPROVED** [review]
ok!

**Pull request merged**
