### PR TITLE
Moving theory files to theories/ directory, and updating makefiles

### PR DESCRIPTION
**Pull request by CohenCyril**
Moving all the Coq files to theories/ directory

### CODE REVIEW

**Comment by CohenCyril** [comment]
@math-comp/analysis please acknowledge

**Comment by drouhling** [comment]
Fine with me.

**Comment by mkerjean** [comment]
fine with me oc

**Comment by affeldt-aist** [comment]
I'm ok (but not tested yet).

**Comment by CohenCyril** [comment]
@affeldt-aist what did you change ?

**Comment by affeldt-aist** [comment]
@CohenCyril I just reset a wrong commit

**Pull request merged**
