### PR TITLE
fubini for s-finite measures

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

This PR contains only one lemma: Fubini for s-finite measure, it comes from the PR on kernels (PR #749 ).

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

### CODE REVIEW

**Review by zstone1 — APPROVED** [review]
Proof makes sense. Personally, I like this style of equational reasoning. The explicit terms appearing in the transitivity calls make it clear how the sums and integrals are moving around. It's very much how a measure theory textbook would feel to read. 

Inspired by agda's equational reasoning stuff, I made a little notation to for formalize it in a different library. See https://github.com/zstone1/coq-complex/blob/master/src/helpers.v around line 170. It has the benefit of being able to `_` away unchanged terms. I'd love to have something like this in mathcomp.  Also it's generalized to any transitive reflexive relation, including `<` and `<=`.

**Comment by affeldt-aist** [comment]
Thanks for taking a look. Indeed, the proof mimics a paper proof presented like equational reasoning, see page 16 of http://www.cs.ox.ac.uk/people/samuel.staton/papers/esop2017.pdf.

**Comment by affeldt-aist** [comment]
> Inspired by agda's equational reasoning stuff, I made a little notation to for formalize it in a different library.
> See https://github.com/zstone1/coq-complex/blob/master/src/helpers.v around line 170.
> It has the benefit of being able to `_` away unchanged terms. I'd love to have something like this in mathcomp.
> Also it's generalized to any transitive reflexive relation, including `<` and `<=`.

Example of use:
https://github.com/zstone1/coq-complex/blob/9ee101eb5b34c30d2e136dd2c080613096c593a1/src/complex_core.v#L485-L495

Indeed, I believe that there are situations where an approach which highlights what's changing improves maintainability despite the extra verbosity.

**Comment by affeldt-aist** [comment]
> I'd love to have something like this in mathcomp.

Do you want to record this as a wish issue before merging?

**Pull request merged**
