### PR TITLE
`opam` file is now compatible with opam2 sandboxing.

### LINKED ISSUE #95: The make install target fails when using opam 2
I'm using opam 2, and the make install target fails, I suspect due to the sandboxing feature. I'm not sure how to solve this exactly, but the other mathcomp packages installed fine, so...

<details><summary>The log</summary>

```
 make -f Makefile.coq install
make[1]: Entering directory '/home/armael/.opam/current/.opam-switch/build/coq-mathcomp-analysis.dev'
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot change permissions of '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis/': No such file or directory
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
install: cannot create directory '/home/armael/.opam/current/lib/coq/user-contrib/mathcomp/analysis': Read-only file system
make[1]: *** [Makefile.coq:471: install] Error 1
make[1]: Leaving directory '/home/armael/.opam/current/.opam-switch/build/coq-mathcomp-analysis.dev'
``` 
</details>

### PR DESCRIPTION
**Pull request by strub**
Fix #95.

### CODE REVIEW

**Comment by strub** [comment]
Maybe waiting the CI to complete before merging is a good baseline :)

**Comment by CohenCyril** [comment]
> Maybe waiting the CI to complete before merging is a good baseline :)

I did...

**Comment by strub** [comment]
I had a mail telling me that the CI failed on my side... I won't try to understand.

**Comment by CohenCyril** [comment]
Commit 5480a961218a4a4868bbf37d21257c44e85a972b was a success: https://circleci.com/gh/math-comp/analysis/358

Commit b1c8355fe0d1ee04f170264a41bbd7c6c745d66c was not: https://circleci.com/gh/math-comp/analysis/357, but I do not understand what this commit refers to...

**Pull request merged**
