### PR TITLE
Issue7

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by CohenCyril** [comment]
@affeldt-aist hi! Can you please rebase on top of master?

**Comment by affeldt-aist** [comment]
Similar PR in branch issue7b (with no merge-commit).

**Comment by CohenCyril** [comment]
Since #50 has been merged, should this one be closed?

**Comment by affeldt-aist** [comment]
> Since #50 has been merged, should this one be closed?
Yes.

**Pull request closed without merging**
