### PR TITLE
Missing results in derive

### PR DESCRIPTION
**Pull request by CohenCyril**
Co-Authored-By: abab9579@gmail.com

##### Motivation for this change

Missing results

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
  (do not edit former entries, only append new ones, be careful:
   merge and rebase have a tendency to mess up `CHANGELOG_UNRELEASED.md`)
- ~~added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

### CODE REVIEW

**Review by zstone1 — APPROVED** [review]
Looks good to me. Mostly just surprised this didn't already exist. There must be some proofs we can refactor with this. Although that's surely a problem for another day.

**Comment by affeldt-aist** [comment]
> Looks good to me. Mostly just surprised this didn't already exist. There must be some proofs we can refactor with this. Although that's surely a problem for another day.

I might have spot a few easy ones, give me some time.

**Comment by affeldt-aist** [comment]
> > Looks good to me. Mostly just surprised this didn't already exist. There must be some proofs we can refactor with this. Although that's surely a problem for another day.

Indeed, the new lemma could be applied at a few places in `derive.v` but this called for some sectioning of the big `Derive` section. I maybe did more than what was strictly needed but imo that improves reading a bit.

**Review by CohenCyril — COMMENTED** [review]
I approve the additional commit (I cannot approve my own PR though)

**Pull request merged**
