### PR TITLE
document the change of order of image arguments

### PR DESCRIPTION
**Pull request by affeldt-aist**
follow up of PR #388

### CODE REVIEW

**Comment by CohenCyril** [comment]
We could also have had `Definition image_def A f := ...` and `Notation image f A := (image_def A f)` :)

**Comment by proux01** [comment]
Thanks!

**Comment by affeldt-aist** [comment]
> We could also have had `Definition image_def A f := ...` and `Notation image f A := (image_def A f)` :)

In our case, we were using `image` in the expression `@image`. Would this notation fit this role?

**Comment by CohenCyril** [comment]
> > We could also have had `Definition image_def A f := ...` and `Notation image f A := (image_def A f)` :)
> 
> In our case, we were using `image` in the expression `@image`. Would this notation fit this role?

no

**Pull request merged**
