### PR TITLE
minor adjustements to `forms.v`

### PR DESCRIPTION
**Pull request by affeldt-aist**
- to avoid clash with ssrbool.symmetric
- remove duplicates

NB: I understand that this file is going to be superseded by MC at some point but in the meantime it is used in coq-robot so these adjustments won't hurt

### CODE REVIEW

**Comment by affeldt-aist** [comment]
oops, I pushed by mistake to master https://github.com/math-comp/analysis/commit/bdf276666be6679a9f6cc0842961d2e15fa7694c which corresponds to one commit of this PR,
I think it is harmless because it is just removal of duplicated things

**Comment by affeldt-aist** [comment]
This is really just to avoid a clash in coq-robot @CohenCyril

**Comment by CohenCyril** [comment]
OK. Can you rename it to `symmetric_form` instead?

**Review by CohenCyril — APPROVED** [review]
ok to merge after rebase

**Pull request merged**
