### PR TITLE
Add the lemma `not_near_ninftyP` in `normedtype.v`

### PR DESCRIPTION
**Pull request by Yosuke-Ito-345**
##### Motivation for this change

@affeldt-aist 
Add an infinite version of the lemma `not_near_at_rightP` in `normedtype.v`.
Tell me if I should write a change log in `CHANGELOG_UNRELEASED.md`.

##### Checklist

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`
- [ ] added corresponding documentation in the headers

Reference: [How to document](https://github.com/math-comp/math-comp/wiki/How-to-document)

##### Reminder to reviewers

- Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs)
- Put a milestone if possible
- Check labels

### CODE REVIEW

**Comment by hoheinzollern** [comment]
Nice work!
I'm unsure about the naming, since the `P` suffix suggests that you move between bool and prop, but the lemma actually changes the statement.
Once the naming is settled, you can add that to CHANGELOG_UNRELEASED.md on a new line.

**Comment by hoheinzollern** [comment]
Ok, that's a pretty valid argument. Would it make sense to add a similar lemma for `not_near_inftyP`?

**Comment by Yosuke-Ito-345** [comment]
Thank you very much.
As you pointed out, I will add the lemma `not_near_inftyP` after this pull request is approved.
I also consider generalizing the lemmas `not_near_at_rightP` and `not_near_at_leftP` (cf. [issue #1723](https://github.com/math-comp/analysis/issues/1273)).

I added my lemma at the `CHANGELOG_UNRELEASED.md`, but the GitHub says that there are conflicts. Should I make another changelog file?

**Comment by affeldt-aist** [comment]
It is maybe better if you provide all the similar-looking lemmas in the same PR: their mutual comparison could help figure out better names and potential factorizations.

As for the changelog conflict, you can do a rebase.

**Comment by Yosuke-Ito-345** [comment]
Sorry, I could not solve my conflict problem by rebase.
(Maybe I did something completely wrong, but I am not sure...)

I created a new [pull request](https://github.com/math-comp/analysis/pull/1291), so could you please review the new one?
I will delete this pull request (#1280) when everything has done.

**Comment by affeldt-aist** [comment]
note that you can add `closes issue #1280` to the PR message of the new PR to close this issue automatically

**Comment by Yosuke-Ito-345** [comment]
I didn't know that!
Thanks for teaching me such a convenient command.

**Comment by affeldt-aist** [comment]
the same contents have made their way into master through the merged PR https://github.com/math-comp/analysis/pull/1291

**Pull request closed without merging**
