### PR TITLE
tentative how-to-release file

### PR DESCRIPTION
**Pull request by affeldt-aist**
This is the same kind of memo as MathComp has for release managers. It might be useful to double-check release steps.

### CODE REVIEW

**Comment by affeldt-aist** [comment]
TODO: make the tag format precise. @CohenCyril

**Comment by CohenCyril** [comment]
> TODO: make the tag format precise. @CohenCyril

done in b264352aaa016e4cdf06054f412af0018bb57fc5

**Comment by CohenCyril** [comment]
@affeldt-aist should we merge this in the Wiki?

**Comment by affeldt-aist** [comment]
> should we merge this in the Wiki?

You mean merge in master (in which case I am ok) or copy-paste in the wiki (in which case I would ask why not merge in master and put a link from the wiki to the .md file)?

**Comment by CohenCyril** [comment]
> > should we merge this in the Wiki?
> 
> You mean merge in master (in which case I am ok) or copy-paste in the wiki (in which case I would ask why not merge in master and put a link from the wiki to the .md file)?

Since this is a release process tied to github and not to the distributed content, I think it should not be in math-comp/analysis, but math-comp/analysis.wiki....

**Comment by affeldt-aist** [comment]
I moved the file to `analysis.wiki`. We can maybe close without merging?

**Pull request closed without merging**
