### PR TITLE
Cherry-picking queue for Hierarchy Builder Port

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

@zstone1 

Can you try to cherry-pick e3972be95eab4bdf550b3a9ab8b190558f82b4e0 (Egerov's theorem)
on top of this PR?

On my side it fails when it tries to apply `uniform_nbhsT` in `lebesgue_measure.v` but
that is maybe I cherry-picked `uniform_nbhsT` wrong in a previous commit?

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] added corresponding documentation in the headers

##### Compatibility with MathComp 2.0

- [ ] I added the label `TODO: HB port` to make sure someone ports this PR to
      the `hierarchy-builder` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

### CODE REVIEW

**Comment by zstone1** [comment]
Just pushed the fix. There were two largely independent issues. Firstly, some (very good and intentional) changes remove canonical filters on arrow types meant we needed to rewrite `f_ --> g` to `f_ @ \oo --> g`. There were also a couple small issues with the proof. Aside from some missing `:`, the interesting issue was in this block
```
apply/uniform_restrict_cvg => /= U /=; rewrite !uniform_nbhsT.
case/nbhs_ex => del /= ballU; apply: filterS; first by move=> ?; exact: ballU.
```
where the `filterS` also needed some help, as `apply: (filterS ballU)` failed rather spectacularly. I managed to get into the rare situation where the proof "succeeds", but the `Qed.` fails. Wild stuff, but it's all resolved now.

**Comment by affeldt-aist** [comment]
@proux0
Am I right to say that the failures in this PR happen in a context where the Coq version is coq-dev?
By the way, the failure is the following one:
```
File "./topology.v", line 4571, characters 25-33:
Error: Anomaly "Unable to handle arbitrary u+k <= v constraints."
```
and failure appears after 60m. These are a bit unusual events and maybe worth noticing.

**Review by zstone1 — APPROVED** [review]
Looks good, pending resolution to the build issue.

**Comment by affeldt-aist** [comment]
Trying to reproduce the erro on my computer, but with coq-dev, I can't compile mathcomp 2.0 and mathcomp dev

**Pull request merged**
