### PR TITLE
Renaming current flim_* to continuous

### PR DESCRIPTION
**Pull request by affeldt-aist**
flim_add -> continuousD
flim_scale -> continuousZ
flim_scalr -> continuousZr
flim_scall -> continuousZl
flim_opp -> continuousN
flim_mult -> limM

created a section for limM and put together
limD and limZl lemmas as corollaries of continuous* lemmas

### CODE REVIEW

**Comment by CohenCyril** [comment]
I am not happy with `limD` (it is more appropriate for `lim (F + G) = lim F + lim G` (under the right convergence hypotheses). That's why I added the `f` prefix. But I was not happy with it too (and it's a bit of Coquelicots heritage too). Let's bring this discussion to #29 before merging.

**Comment by CohenCyril** [comment]
Also, continuous being a unary predicate, it should be a suffix as in `add_continuous` etc...

**Comment by drouhling** [comment]
I agree with `add_continuous`; `continuousD` is more appropriate for
`continuous f -> continuous g -> continuous (f + g)`, which is a consequence of
`add_continuous` and `continuous_comp` (still to be proven).

**Comment by CohenCyril** [comment]
@affeldt-aist thanks for the update, but can you rebase your branch against the current master?

**Comment by CohenCyril** [comment]
I did the rebase. Waiting for CI to check then merge

**Pull request merged**
