### PR TITLE
[opam]: add dev-repo

### PR DESCRIPTION
**Pull request by anton-trunov**
Please see https://github.com/coq/opam-coq-archive/pull/456 for details.

### CODE REVIEW

**Comment by strub** [comment]
`git+https` is a valid scheme ? Because `git` is bugging on it.

**Comment by anton-trunov** [comment]
@strub Oh, shoot, you are right! I copied it from here: https://github.com/coq/opam-coq-archive/blob/30ca50d426ab4e54a5c496774483eb58debb1b7e/extra-dev/packages/coq-mathcomp-multinomials/coq-mathcomp-multinomials.dev/opam#L5

**Comment by anton-trunov** [comment]
And Coq does not have this `git+` prefix: https://github.com/coq/coq/blob/016f4a302090bcbb4ad47197dda2c60d6f598f6a/coq.opam#L6

Sorry for the noise and let me quickly force-push a correction.

**Comment by strub** [comment]
That's unfair to point my own mistakes :)

**Comment by anton-trunov** [comment]
Thanks for merging! I'm gonna go and fix the packages in the coq-opam archive :)

**Pull request merged**
