### PR TITLE
Add lemmas on divergent sequences

### LINKED ISSUE #1261: Adding the infinite versions of lemmas such as `cvg_at_rightP` in `realfun.v`
I am trying to formalize the infinite versions of lemmas in `Section cvgr_fun_cvg_seq` in `realfun.v`.
Some candidates are as follows.
```
Lemma cvg_ninftyP (f : R -> R) (l : R) :
  f x @[x --> -oo] --> l <->
  (forall u : R^nat, (u n @[n --> \oo] --> -oo) -> f (u n) @[n --> \oo] --> l).
```
```
Lemma cvg_pinftyP (f : R -> R) (l : R) :
  f x @[x --> +oo] --> l <->
  (forall u : R^nat, (u n @[n --> \oo] --> +oo) -> f (u n) @[n --> \oo] --> l).
```
If anybody is trying the same thing, please let me know to avoid duplicate work.
Since I am new to MathComp-Analysis, any advice is welcome.

### PR DESCRIPTION
**Pull request by Yosuke-Ito-345**
##### Motivation for this change

fixes #1261 

@affeldt-aist @hoheinzollern 
Add lemmas `cvg_pinftyP` and `cvg_ninftyP` in `realfun.v`.
These are the infinite versions of lemmas `cvg_at_leftP` and `cvg_at_rightP`.

##### Checklist

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
- [ ] added corresponding documentation in the headers

Reference: [How to document](https://github.com/math-comp/math-comp/wiki/How-to-document)

##### Reminder to reviewers

- Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs)
- Put a milestone if possible
- Check labels

### CODE REVIEW

**Comment by Yosuke-Ito-345** [comment]
Sorry, there are bugs.
I made a mistake again...
I will fix them later.

**Comment by Yosuke-Ito-345** [comment]
The bugs seem to be removed.
Could you review the code?

**Comment by Yosuke-Ito-345** [comment]
Could anyone review this PR?

**Comment by affeldt-aist** [comment]
it looks like this PR is adding `.DS_Store` files to
`classical`, `theories`, and `altreals`, they should be removed

**Review by affeldt-aist — APPROVED** [review]
@hoheinzollern , ok to merge if the CI turns green?

**Pull request merged**
