### PR TITLE
Add lemmas on subtraction of extended values

### PR DESCRIPTION
**Pull request by proux01**
Sometime, the variable I want to move around is the extended one and not the finite one. Adding a few lemmas for that case. Not completely sure about the naming.

### CODE REVIEW

**Review by affeldt-aist — COMMENTED** [review]
I am wondering whether `lte_suble_addr` and `lte_suble_addl` are the lemmas you intended.

**Comment by proux01** [comment]
Indeed, I copy pasted those without enough thinking, they are definitely useless. Let me fix that.

**Comment by proux01** [comment]
@affeldt-aist thanks for your remark, I thought about this a bit more carefully and came up with a naming scheme I'm happy with for this family of lemmas: `l{t,e}e_{,d}sub{,e}{r,l}_add{r,l}` with
* sub{r,l} when the subtracted var must be a fin_num
* sube{r,l} when the subtracted var can be an extended value (and one of the two other vars must be a fin_num)

This is now a full cartesian product (all 32 lemmas are there).

**Review by affeldt-aist — APPROVED** [review]
I do not see any problem.

**Pull request merged**
