### PR TITLE
minor generalization

### PR DESCRIPTION
**Pull request by affeldt-aist**
Co-authored-by: @AyumuSaito

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

### CODE REVIEW

**Comment by affeldt-aist** [comment]
I will maybe merge this one soon because it is small and looks fine to me.

**Review by proux01 — APPROVED** [review]
Sorry for the late review. LGTM, let's merge (just rerunning CI).

**Comment by proux01** [comment]
@affeldt-aist according to the CI, there is an issue on Coq 8.13

**Comment by affeldt-aist** [comment]
> @affeldt-aist according to the CI, there is an issue on Coq 8.13

Indeed. It looks like a notation problem. Aren't we suppose to drop 8.13 soon? (When 8.16 is available?).

**Comment by proux01** [comment]
I'm perfectly fine with dropping 8.13.

**Pull request merged**
