### PR TITLE
Covariance inequality

### PR DESCRIPTION
**Pull request by proux01**
Depends on ~https://github.com/math-comp/math-comp/pull/1002~ (merged) and https://github.com/math-comp/analysis/pull/918 so kept as draft for now.

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`

- [ ] ~added corresponding documentation in the headers~

##### Compatibility with MathComp 2.0

- [x] I added the label `TODO: HB port` to make sure someone ports this PR to
      the `hierarchy-builder` branch **or** I already opened an issue or PR (please cross reference).

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-creating-and-review-PRs) and put a milestone if possible.

### CODE REVIEW

**Comment by proux01** [comment]
CI green. This might look large but it really is a single lemma (c.f. second commit), all the remaining is "backporting" from mathcomp.

**Comment by proux01** [comment]
Rebased and simplified after the merge of https://github.com/math-comp/analysis/pull/932 CI green again.

**Review by affeldt-aist — COMMENTED** [review]
I felt that the ratio of technicalities/proof in `covariance_le` was not very good (by technicalities I mean essentially conversions from `\bar R` to `R` (partly using `set` and `case`, partly using `lee_fin`) and going from 3 variables to a polynomial) so I tried to extract that part about the "polynomial conversion" (because the one about `\bar R`/`R` seems more difficult) and it looked to me that the proof is now clearer. One might wonder whether the specialization `deg_le2_ge0` is worth having but that is such an idiomatic lemma (almost as the same level as "identite remarquable") that I would say yes. What do you think?

**Comment by proux01** [comment]
Thanks, that's indeed much better. I just added a comment to remember that the new lemma is not backported.
I also fixed compilation with old mathcomp still in CI. CI green now, I think this can be merged.

**Pull request merged**
