### PR TITLE
replace Grab by Unshelve

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by proux01** [comment]
You should probably edit `meta.yml` and regenerate OPAM, Nix,... files (c.f.  https://github.com/coq-community/templates ) to drop 8.11 and 8.12. And we should probably also update the OPAM package on extra-dev before merging.

**Comment by affeldt-aist** [comment]
> we should probably also update the OPAM package on extra-dev before merging.

You mean the files in `opam-coq-archive/extra-dev/packages/coq-mathcomp-analysis`?
(Because it is a long time we haven't touched those. :-( )

**Comment by affeldt-aist** [comment]
"Nix CI for bundle 8.11 / mathcomp-analysis (pull_request)" fails
while "Nix CI for bundle 8.11 / coq (pull_request)" succeeds.
I would have expected all 8.11 CIs to fail...

**Comment by proux01** [comment]
> You mean the files in `opam-coq-archive/extra-dev/packages/coq-mathcomp-analysis`?

yep (we can just bump Coq 8.11 to 8.13 and take the opportunity to tell ssreflect 1.13 is supported)

> "Nix CI for bundle 8.11 / coq (pull_request)" is marked as a success but if we click on "Details" we can observe that compilation is incomplete.

I don't get your point, it looks to me like Coq 8.11 was successfully retrieved from cachix?

**Comment by affeldt-aist** [comment]
> I don't get your point, it looks to me like Coq 8.11 was successfully retrieved from cachix?

I see. I didn't understand that the point of this part of the CI was to check only that Coq can be retrieved.Thank you.

**Comment by proux01** [comment]
@affeldt-aist this now looks mergeable

**Comment by proux01** [comment]
It remains to remove 8.11 and 8.12 from Nix CI, removing the two bundle lines in `.nix/config.nix` and the two corresponding files in `.github/workflows` should be enough.

**Comment by proux01** [comment]
So addition of Analysis in Coq CI is waiting for this to be merged: https://github.com/coq/coq/pull/15443

**Pull request merged**
