### PR TITLE
move contents of equiv.v to landau.v and document

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by affeldt-aist** [comment]
You are right. How about I open a new issue about Omega and Theta? I would like to prove a few more properties about them and I may not be able to do it soon. Yet, since this PR involves file deletion, it is maybe better to merge it now.

**Comment by drouhling** [comment]
Agreed.

I suggest:
1. adding a very short documentation for Omega and Theta, saying explicitly that it is WIP, so that their existence is at least mentioned;
2. merging this PR after this addition and open an issue for the missing properties;
3. writing a more precise documentation once these properties are proven.

**Comment by affeldt-aist** [comment]
Following drouhling's comment, I have added a few words about the existence of Omega and Theta and their wip status, update the file with wip, and rebased the issse33 branch on top of the current master branch. Issue33 to be kept opened until work on Omega and Theta is completed. Can maybe be merged to get rid of equiv.v.

**Comment by drouhling** [comment]
Cleaned up the history, ready to merge.

**Pull request merged**
