### PR TITLE
distinguish between nnesum and esum

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

To prove lemmas required for probability.v.

This PR is scheduled to be closed in the near future (once PR #628 is merged (?))

@t6s 

##### Things done/to do

- [ ] added corresponding entries in `CHANGELOG_UNRELEASED.md`
  (do not edit former entries, only append new ones, be careful:
   merge and rebase have a tendency to mess up `CHANGELOG_UNRELEASED.md`)
- [ ] added corresponding documentation in the headers

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

### CODE REVIEW

**Comment by affeldt-aist** [comment]
So the generalization of \esum should be constructed as an instance of the theory of integral?

**Comment by CohenCyril** [comment]
Yes and then you even recover the cvd and fubini and cool stuff for free.
Actually even the current `esum` is only there for bootstrapping...

**Comment by affeldt-aist** [comment]
Will do.

**Comment by affeldt-aist** [comment]
The goal of this draft PR was mainly to produce the following lemma to prove countable additivity:
```coq
Lemma esumB D f g : esummable D f -> esummable D g ->
  (forall i, D i -> 0 <= f i) -> (forall i, D i -> 0 <= g i) ->
  \esum_(i in D) (f i - g i) = \esum_(i in D) f i - \esum_(i in D) g i.
  ```
but it was introducing sequences of arbitrary extended real numbers for this purpose.
The following lemma made its way into master, is equally useful, and does not require the introduction of new definition: 
```coq
Lemma esumB D f g : summable D f -> summable D g ->
  (forall i, D i -> 0 <= f i) -> (forall i, D i -> 0 <= g i) ->
  \esum_(i in D) (f \- g)^\+ i - \esum_(i in D) (f \- g)^\- i =
  \esum_(i in D) f i - \esum_(i in D) g i.
  ```
  I therefore close this draft PR.

**Pull request closed without merging**
