### PR TITLE
fixes #486

### LINKED ISSUE #486: usefulness of `nbhs_pinfty_gt_pos`
https://github.com/math-comp/analysis/blob/87030d669403157aff8dbb676fa901521a03a131/theories/normedtype.v#L518

Is `nbhs_pinfty_gt_pos` really necessary? Isn't it subsumed by `nbhs_pinfty_gt`:

https://github.com/math-comp/analysis/blob/87030d669403157aff8dbb676fa901521a03a131/theories/normedtype.v#L512

Note that both are actually used as of today.

### PR DESCRIPTION
**Pull request by affeldt-aist**
##### Motivation for this change

fixes #486 

based on PR #511

##### Things done/to do

- [x] added corresponding entries in `CHANGELOG_UNRELEASED.md`
  (do not edit former entries, only append new ones, be careful:
   merge and rebase have a tendency to mess up `CHANGELOG_UNRELEASED.md`)
~~- [ ] added corresponding documentation in the headers~~

##### Automatic note to reviewers

Read [this Checklist](https://github.com/math-comp/math-comp/wiki/Checklist-for-following,-reviewing-and-playing-with-a-PR#checklist-for-reviewing-a-pr) and put a milestone if possible.

### CODE REVIEW

**Review by zstone1 — APPROVED** [review]
Looks good to me. 

Possibly as a separate change, it would be nice to have some automation for `rewrite realM// posnum_real`. Maybe something as lightweight as a hint would suffice. Or will this all change in the new Posnum stuff?

**Comment by proux01** [comment]
Indeed, there should be a hint in the new posnum stuff, we should try.

**Comment by affeldt-aist** [comment]
Then I'll merge and issue not to forget about testing some automation.

**Comment by affeldt-aist** [comment]
> I strongly prefer to waìt until the posnum PR is merged

Do you mean that it is not sure that we'll get rid of the lemmas after all?

**Comment by CohenCyril** [comment]
> Do you mean that it is not sure that we'll get rid of the lemmas after all?

I mean that it seems to be a detour to "merge this, open an issure, merge https://github.com/math-comp/analysis/issues/486, then fix the issue by (hopefully) restoring the old proofs", rather than "finishing #486, amending this PR, merge"

**Comment by affeldt-aist** [comment]
To use the new posnum, I needed to rebase it but it was too difficult to retain its intermediate commits. I therefore squashed it, rebased it, and then rebased this PR on top of it so as to propagate the automation it provides to the files that change in the meantime in master. The new posnum addressed the comments by Zachary. I kept all the technical comments about the new posnum into the commit message of the squashed commits.

**Comment by proux01** [comment]
Great, thanks! I did a finer rebase to keep a bit more history in https://github.com/math-comp/analysis/pull/511

**Comment by affeldt-aist** [comment]
> Great, thanks! I did a finer rebase to keep a bit more history in #511

I rebased on the new #511. That addresses the pending change request.

**Review by CohenCyril — APPROVED** [review]
Rebase & merge

**Pull request merged**
