### PR TITLE
update toolbox

### PR DESCRIPTION
**Pull request by CohenCyril**

### CODE REVIEW

**Comment by proux01** [comment]
The failure for Coq master comes from https://github.com/coq/coq/pull/15220

**Comment by CohenCyril** [comment]
> The failure for Coq master comes from [coq/coq#15220](https://github.com/coq/coq/pull/15220)

:sob:

**Comment by proux01** [comment]
@CohenCyril I uncommented Coq master in config.nix but we now have a Cachix error: https://github.com/math-comp/analysis/runs/6725051905?check_suite_focus=true

**Comment by CohenCyril** [comment]
> @CohenCyril I uncommented Coq master in config.nix but we now have a Cachix error: https://github.com/math-comp/analysis/runs/6725051905?check_suite_focus=true

Looks like a cachix error... I reran it

**Comment by proux01** [comment]
Looks like you aren't luckyer than me :(

**Comment by CohenCyril** [comment]
coq master looks broken for other reasons now :-/

**Comment by proux01** [comment]
I handled that in the HB port, let me fix it.

**Comment by proux01** [comment]
This now works but with a few overlays. Let me backport them.

**Pull request merged**
