### PR TITLE
Split boolp, classical_sets,... in a new mathcomp-classical package

### LINKED ISSUE #550: Create a `mathcomp-classical` opam package
Following a discussion on Zulip (https://coq.zulipchat.com/#narrow/stream/237666-math-comp-analysis/topic/boolp) and during the last mca meeting (https://github.com/math-comp/analysis/wiki/2022-02-24-Meeting).

Put `boolp.v` and `classical_sets.v` in a separate package (say `mathcomp-classical`) to be released as an individual opam package (like it is done for mathcomp). Would require proper documentation of `boolp.v` first though.

### PR DESCRIPTION
**Pull request by proux01**
Fixes #550 

Classical currently contains boolp and classical_sets, we may also consider adding functions and signed there.

### CODE REVIEW

**Comment by affeldt-aist** [comment]
> we may also consider adding functions and signed there.

I would maybe refrain to do so for now because we didn't have (yet?) explicit requests for them and `functions.v` requires more dependencies and this has consequences on compilation time.

**Comment by affeldt-aist** [comment]
i think that at some point it was scheduled to replace bigenough

**Comment by CohenCyril** [comment]
> i think that at some point it was scheduled to replace bigenough

it is, actually near is neither analysis nor classical :smile:

**Comment by proux01** [comment]
@affeldt-aist has a good point that mathcomp-classical may, in the current state of the PR, be larger than what @strub initially requested.

What about cutting it in three instead?
* mathcomp-classical: with boolp and classical_sets, only requiring mathcomp-ssreflect
* mathcomp-reals: everything else not strictly pertaining to topology/calculus/analysis, requiring mathcomp-algebra and HB
* mathcomp-analysis: topology/calculus/analysis

**Comment by CohenCyril** [comment]
> What about cutting it in three instead?
> 
> * mathcomp-classical: with boolp and classical_sets, only requiring mathcomp-ssreflect
> * mathcomp-reals: everything else not strictly pertaining to topology/calculus/analysis, requiring mathcomp-algebra and HB
> * mathcomp-analysis: topology/calculus/analysis

I disagree with this. I have no objection to merge reals and analysis, but I believe that:
- `boolp.v`
- `classical_sets.v`
- `cardinality.v`
- `fsbigop.v
- `functions.v` (not in mathcomp just because of HB + a light separation between the constructive and classical part should be done)
belong to classical.

On the other hand `forms.v` (PR in progress for a while) and `mathcomp_extra.v` (easy stuff) have to be merged in mathcomp.
Also `nngnum.v`, `posnum.v` and `signed.v` do belong to mathcomp too.

**Comment by CohenCyril** [comment]
We should discuss this at the next mc analysis meeting

**Comment by proux01** [comment]
So, here is a classical package with only
* `boolp.v`
* `classical_sets.v`
* `cardinality.v`
* `fsbigop.v`
* `functions.v`
* the part of `set_interval.v` that doesn't depend on reals or ereal

The classical package depends on HB (because of functions) but I think it's fine as MC 2.0 will depend on it anyway.

Reals and ereal should probably go in another separate package but I think this belongs to a further PR.
BTW, ereal should maybe be split between its classic and non classic part.

**Comment by CohenCyril** [comment]
Sorry for the delay. This looks nice. We also need to take care of the nix packages when we do this.

**Comment by proux01** [comment]
Rebased (hope will manage to merge this "soon", because those rebases are rather painful)

**Comment by affeldt-aist** [comment]
> Rebased (hope will manage to merge this "soon", because those rebases are rather painful)

**Comment by proux01** [comment]
CI green, this requires:
* for Nix: https://github.com/NixOS/nixpkgs/pull/184961 on nixpkgs, then https://github.com/coq-community/coq-nix-toolbox/pull/117 on coq-nix-toolbox (we could then update coq-nix-toolbox here and remove the overlays)
* for OPAM: a PR on extra-dev

**Comment by CohenCyril** [comment]
Hi @proux01 the overlays should be unnecessary (since you merged the nixpkgs pr), however this made me noticed that a `mathcomp-analysis-single` package would be convenient for dev and CI purposes (as in https://github.com/NixOS/nixpkgs/blob/2a48d5921115733b840e651b843a3c7c515db582/pkgs/development/coq-modules/mathcomp/default.nix#L54).
I'm sorry this is undocumented. The purpose of this package is to be able to build everything in a single `make`

**Comment by proux01** [comment]
> Hi @proux01 the overlays should be unnecessary (since you merged the nixpkgs pr)

@CohenCyril right, removed. Ci is as green as expected (there is still this master failure with this strange dependency to real-closed that we should fix, but that's orthogonal to the current PR).

> however this made me noticed that a `mathcomp-analysis-single` package would be convenient for dev and CI purposes (as in https://github.com/NixOS/nixpkgs/blob/2a48d5921115733b840e651b843a3c7c515db582/pkgs/development/coq-modules/mathcomp/default.nix#L54). I'm sorry this is undocumented. The purpose of this package is to be able to build everything in a single `make`

Done there: https://github.com/NixOS/nixpkgs/pull/193162 (and successfully tested on the coq-nix-toolbox there: https://github.com/coq-community/coq-nix-toolbox/pull/122)

I'll do the OPAM packages in extra-dev once this is merged

**Comment by proux01** [comment]
@CohenCyril Nix CI green (the Docker CI failure seems unrelated and is likely due to this: https://github.com/math-comp/math-comp/pull/924)
So I think the current PR can be merged (I'll then update the extra-dev OPAM packages).

**Comment by proux01** [comment]
@CohenCyril CI "green" (the Docker failures are exepected due to the exhaustion of gitlab credits), including the `mathcomp-analysis-single` package.

**Comment by CohenCyril** [comment]
Fantastique !

**Comment by gares** [comment]
Classy ;-)

**Comment by proux01** [comment]
OPAM package done, we should be all set.

**Pull request merged**
