### PR TITLE
Make set image a (only parsing) notation, 2nd take

### PR DESCRIPTION
**Pull request by proux01**
This fixes the issue identified by @affeldt-aist in https://github.com/math-comp/analysis/pull/362#issuecomment-856430030 applying the fix suggested by @CohenCyril in https://github.com/math-comp/analysis/pull/362#issuecomment-858362396

### CODE REVIEW

**Comment by proux01** [comment]
It works better for type inference. I don't know whether it is such a fundamental thing or just the result of the previous notation that was written in that order (`exists2 x, A x & f x = y` rather than `exists2 x, f x = y & A x`) though.

**Comment by affeldt-aist** [comment]
Would it be ok to merge this and make a minor release of MathComp-Analysis?

**Comment by affeldt-aist** [comment]
Hasn't the order of the arguments of `image` change from 0.3.7?

**Comment by proux01** [comment]
Yes, c.f. the discussion in #388 . The ` [set E | x in A]` notation was written as `exists2 x, A x & f x = y` and the order `image A f` enabled to get similar type inference results. With the previous order `image f A`, quite a few extra type casts were needed to make analysis itself compile.

**Comment by CohenCyril** [comment]
I did not think enough about this. We should at least document the breaking change.

**Pull request merged**
